---
- name: Change local admin account password to a random
  hosts: all

  tasks:
    - name: Ensure that Administrator user present
      win_user:
        name: Administrator
        state: present
        password_never_expires: no
        groups:
          - Administrators
      register: results

    - name: Display user password expiration
      debug:
        msg: "Password Expired: {{ results.password_expired }}  Password Never Exprires: {{ results.password_never_expires }}"

    - block:
        - name: Generate random password
          random_generator:
            size: 14
          register: new_password
          delegate_to: 127.0.0.1

        - name: Write the generated password to the file
          blockinfile:
            path: "./generated/{{ ansible_nodename }}.txt"
            block: |
              {{ ansible_nodename }}
              {{ new_password.msg }}
            create: yes
          delegate_to: 127.0.0.1

        - name: Change Administrator Password
          win_user:
            name: Administrator
            password: "{{ new_password.msg }}"
            password_expired: no


      rescue:
        - name: Changing password fail
          debug:
            msg: "Failed to change password"

      when: results.password_expired == true
